### ISSUE TITLE
RuntimeError ：Missing key(s) in state_dict: "bert.embeddings.position_ids".

### ISSUE THREAD

**Issue by 18166035475** [vitouphy/usl_dialogue_metric#1]
when I run predict.py,the error happen in loading state_dict for VUPScorer
![Uploading image.png…]()

**Comment by 18166035475** [comment]
![image](https://user-images.githubusercontent.com/36977255/130625192-83dff63d-58c7-4e22-bce3-0e41db839c26.png)

**Comment by ghost** [comment]
I have the same question。U solve it?
